version: "3.5"
services:
  ldap:
    image: verizon/me/openldap
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      LDAP_HOST:           "ldap"
      LDAP_BASEDN:         "dc=ienlab,dc=verizon,dc=com"
      LDAP_ADMIN_USER:     "admin"
      LDAP_ADMIN_PASSWORD: "XXXXXXXXXXX"
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    networks:
      - net
    ports:
      - target: 389
        published: 389
        protocol: tcp
        mode: host
    volumes:
      - "/opt/docker/aaa/ldap/config:/etc/openldap/slapd.d"
      - "/opt/docker/aaa/ldap/data:/var/lib/openldap/openldap-data"
  phpldapadmin:
    image: verizon/me/phpldapadmin
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - ldap
    environment:
      LDAP_HOST:           "ldap"
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    networks:
      - net
    ports:
      - "80:8080/tcp"
  tacplus:
    image: verizon/me/tacplus
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - ldap
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    networks:
      - net
    ports:
      - target: 49
        published: 49
        protocol: tcp
        mode: host
    tty: true
    volumes:
      - "/opt/docker/aaa/tacplus/tac_plus.cfg:/tacacs/etc/tac_plus.cfg"
  radius:
    image: verizon/me/freeradius
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - ldap
    environment:
      LDAP_HOST:           "ldap"
      LDAP_BASEDN:         "dc=ienlab,dc=verizon,dc=com"
      LDAP_ADMIN_USER:     "admin"
      LDAP_ADMIN_PASSWORD: "XXXXXXXXXXX"
      LDAP_ADMIN_FULLDN:   "cn=admin,dc=ienlab,dc=verizon,dc=com"
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    networks:
      - net
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - "/opt/docker/aaa/radius/users:/etc/raddb/mods-config/files/authorize"
      - "/opt/docker/aaa/radius/huntgroups:/etc/raddb/mods-config/preprocess/huntgroups"
      - "/opt/docker/aaa/radius/clients.conf:/etc/raddb/clients.conf"

networks:
  net:
